name: Using Reusable Workflows
run-name: Deploy by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: wo-o/demo-reusable-workflow/.github/workflows/main.yml@main
    with:
      app-name: 'demo-app'
      image-tag: '1.19.10'
      environment: 'dev'
    secrets:
      git_token: ${{ secrets.GIT_TOKEN }}
