Resources:
  VideoConvertLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${file(./custom.yml):custom.lambdaRoleName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ${file(./custom.yml):custom.lambdaPolicyName}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mediaconvert:CreateJob
                  - mediaconvert:GetJob
                  - mediaconvert:ListJobs
                  - mediaconvert:DescribeEndpoints
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: ${file(./custom.yml):custom.s3BucketResources}
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt MediaConvertRole.Arn

  MediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${file(./custom.yml):custom.mediaConvertRoleName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: mediaconvert.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${file(./custom.yml):custom.mediaConvertPolicyName}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowS3Access
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: ${file(./custom.yml):custom.s3BucketResources}
